### ISSUE TITLE
pre-install / qstat / autogen.sh not committed

### ISSUE THREAD

**Issue by ramses0** [amineo/discord-battlebot#8]
...as says, trying to get it up and running locally on my host. :-)

**Comment by amineo** [comment]
I'm going to put together docs and comments on the codebase now that its more stable. It went under a major refactor not too long ago :) (still doesn't excuse my lack of comments)

---

**So here are a few steps & things you'll need to get BattleBot up and running locally.**

 - Clone the repo
- Pull in the Submodules (qstat) with git submodule init/update
```
  git submodule init
  git submodule update
  ```
 - `npm install` (this should also build qstat)
 -  You will need to set 3 env vars. I created a dev.sh that sets all my environment vars before it loads BattleBot. The env that its running in: *dev*, A Steam WebAPI Key, and a Discord Bot Token.
```
#!/bin/bash
NODE_ENV=dev STEAM_KEY=YOUR_STEAM_KEY DISCORD_TOKEN=YOUR_DISCORD_BOT_TOKEN nodemon battlebot.js
```

I'd also recommend installing `nodemon` so that BattleBot auto-reloads when you make a change. 
```npm install -g nodemon```

So with that script in place, I can just run `dev.sh` and everything loads up with those env vars and as I make changes to BattleBot he auto-reloads

Hope this helps!

**Comment by amineo** [comment]
Thanks! Installation and steps to setup have been added to the README.md
